language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc
 - g++

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - make distcheck
 - make distclean
 - ./configure --disable-dependency-tracking --enable-minimal
 - make distcheck

env:
  global:
   - secure: "P4qv8aX+nogLlSy0lTMDIR6I5OLXq+qMijB4s+oCLME5BL2xPAn3v0QG5IoHdnU0ncRc1tEYZxN3F48Rp+Q7+wEVqSBLFS3oXzfNHJGEYoiaAcPNWO0R1kF8rcy8AuoAEomNeYS+5vhzQtaXklNtx/250p6MgGuMsdpMsRUKS/U="

addons:
  coverity_scan:
    project:
      name: "jedisct1/libsodium"
      description: "libsodium"
      notification_email: coverityscan@pureftpd.org
      build_command_prepend: "./autogen.sh ; ./configure"
      build_command: "make -j4"
      branch_pattern: coverity_scan
